from django.urls import path,include
from . import views
urlpatterns = [
    path('staff/', views.StaffView.as_view()),
    path('staff/<int:id>', views.StaffDetail.as_view()),
    path('patient/', views.PatientView.as_view()),
    path('patient/<int:num>', views.PatientDetail.as_view()),
    path('pharmaceutical/', views.PharmaceuticalView.as_view()),
    path('pharmaceutical/<int:id>', views.PharmaceuticalDetail.as_view()),
    path('drug/', views.DrugView.as_view()),
    path('drug/<int:id>', views.DrugDetail.as_view()),
    path('vitamin_herb/', views.VitaminHerbView.as_view()),
    path('vitamin_herb/<int:id>', views.VitaminHerbDetail.as_view()),
    path('medicine_case/', views.MedicineCaseView.as_view()),
    path('medicine_case/<int:num>', views.MedicineCaseDetail.as_view()),
    path('medicine_case/<int:num>$<int:id>', views.MedicineCasePatientPharmDetail.as_view()),
    path('medical_unit/', views.MedicalUnitView.as_view()),
    path('medical_unit/<int:num>', views.MedicalUnitDetail.as_view()),
    path('medical_bed/', views.MedicalBedView.as_view()),
    path('medical_bed/<int:unit>', views.MedicalBedDetail.as_view()),
    path('medical_bed/<int:unit>$<int:number>', views.MedicalBedPair.as_view()),
    path('supplier/', views.SupplierView.as_view()),
    path('supplier/<str:name>', views.SupplierDetail.as_view()),
    path('delivery/', views.DeliveryView.as_view()),
    path('delivery/<int:num>', views.DeliveryDetail.as_view()),
    path('supplies/', views.SuppliesView.as_view()),
    path('supplies/<str:supplier>', views.SuppliesSupplierDetail.as_view()),
    path('supplies/<str:supplier>/$<int:num>', views.SuppliesSupplierDeliveryDetail.as_view()),
    path('location/', views.SupplierLocationView.as_view()),
    path('location/<str:sup>', views.SupplierLocationDetail.as_view()),
    path('location/<str:sup>/$<str:loc>', views.SupplierLocationPair.as_view()),
    path('delivery_content/', views.DeliveryContainsView.as_view()),
    path('delivery_content/<int:num>', views.DeliveryContainsDetail.as_view()),
    path('delivery_content/<int:num>$<int:id>', views.DeliveryContainsDelPharmDetail.as_view()),
    path('carriedOutBy/', views.CarriedOutByView.as_view()),
    path('carriedOutBy/<int:num>', views.CarriedOutByDetail.as_view()),
    path('diagnosis/', views.DiagnosisView.as_view()),
    path('diagnosis/<int:num>', views.DiagnosisPatientDetail.as_view()),
    path('diagnosis/<int:num>$<int:id>', views.DiagnosisPatientPharmDetail.as_view()),
    path('nurse_order/', views.NurseOrderView.as_view()),
    path('nurse_order/<int:num>', views.NurseOrderPatientDetail.as_view()),
    path('nurse_order/<int:num>$<int:id>', views.NurseOrderPatientPharmDetail.as_view())
]