# Generated by Django 4.0 on 2022-02-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_posting_posting_passenger_report_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posting_Passenger',
            new_name='PostingPassenger',
        ),
        migrations.AddField(
            model_name='posting',
            name='endTime',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
    ]
