# Generated by Django 4.0 on 2021-12-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('healthcareNum', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('primaryNurseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primaryNurse', to='api.staff')),
                ('secondaryNurseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondaryNurse', to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientHealthcareNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
