# Generated by Django 4.0 on 2021-12-22 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_medicine_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField()),
                ('medCase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryMedCase', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryContains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfPharmaceutical', models.IntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containsDelivery', to='api.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfPharmaceutical', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosisDoctor', to='api.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosisPatient', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalUnit',
            fields=[
                ('Number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCaseContains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfPharmaceutical', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NurseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfPharmaceutical', models.IntegerField()),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NurseOrderNurse', to='api.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NurseOrderPatient', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmaceutical',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('numberInStock', models.IntegerField()),
                ('IdPharmaceutical', models.IntegerField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliesDelivery', to='api.delivery')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliesSupplier', to='api.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'delivery')},
            },
        ),
        migrations.CreateModel(
            name='CarriedOutBy',
            fields=[
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='carriedOutByDelivery', serialize=False, to='api.delivery')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriedOutByPharmacist', to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('DIN', models.IntegerField(max_length=255)),
                ('IdPharmaceutical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pharmaceutical')),
            ],
        ),
        migrations.CreateModel(
            name='VitaminHerb',
            fields=[
                ('VIN', models.IntegerField(max_length=255)),
                ('IdPharmaceutical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pharmaceutical')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicine_Case',
        ),
        migrations.AddField(
            model_name='nurseorder',
            name='pharmaceutical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NurseOrderPharmaceutical', to='api.pharmaceutical'),
        ),
        migrations.AddField(
            model_name='medicinecasecontains',
            name='IdPharmaceutical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madCasePharmaceutical', to='api.pharmaceutical'),
        ),
        migrations.AddField(
            model_name='medicinecasecontains',
            name='patientHealthcareNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medCasePatient', to='api.patient'),
        ),
        migrations.AddField(
            model_name='medicalbed',
            name='medUnitNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicalUnit', to='api.medicalunit'),
        ),
        migrations.AddField(
            model_name='medicalbed',
            name='occupyingPatientNum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bedPatient', to='api.patient'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='pharmaceutical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiagnosisPharmaceutical', to='api.pharmaceutical'),
        ),
        migrations.AddField(
            model_name='deliverycontains',
            name='pharmaceutical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containsPharmaceutical', to='api.pharmaceutical'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverySupplier', to='api.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='nurseorder',
            unique_together={('patient', 'pharmaceutical')},
        ),
        migrations.AlterUniqueTogether(
            name='medicinecasecontains',
            unique_together={('patientHealthcareNum', 'IdPharmaceutical')},
        ),
        migrations.AlterUniqueTogether(
            name='medicalbed',
            unique_together={('Number', 'medUnitNumber')},
        ),
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together={('patient', 'pharmaceutical')},
        ),
        migrations.AlterUniqueTogether(
            name='deliverycontains',
            unique_together={('delivery', 'pharmaceutical')},
        ),
    ]
