# Generated by Django 4.0 on 2021-12-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='IdPharmaceutical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='drugPharmaceutical', serialize=False, to='api.pharmaceutical'),
        ),
        migrations.AlterField(
            model_name='vitaminherb',
            name='IdPharmaceutical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vitaminHerbPharmaceutical', serialize=False, to='api.pharmaceutical'),
        ),
    ]
