# Generated by Django 4.0 on 2021-12-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_drug_idpharmaceutical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriedoutby',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='carriedOutByDelivery', serialize=False, to='api.delivery'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='DIN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='IdPharmaceutical',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pharmaceutical'),
        ),
        migrations.AlterField(
            model_name='vitaminherb',
            name='IdPharmaceutical',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pharmaceutical'),
        ),
        migrations.AlterField(
            model_name='vitaminherb',
            name='VIN',
            field=models.IntegerField(),
        ),
    ]
