# Generated by Django 4.0 on 2021-12-22 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_carriedoutby_delivery_alter_drug_din_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinecasecontains',
            name='IdPharmaceutical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medCasePharmaceutical', to='api.pharmaceutical'),
        ),
    ]
