# Generated by Django 4.0 on 2021-12-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_idpharmaceutical_drug_idpharmaceutical_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='idPharmaceutical',
            new_name='IdPharmaceutical',
        ),
        migrations.RenameField(
            model_name='medicalbed',
            old_name='number',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='medicalunit',
            old_name='number',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='medicinecasecontains',
            old_name='idPharmaceutical',
            new_name='IdPharmaceutical',
        ),
        migrations.RenameField(
            model_name='pharmaceutical',
            old_name='idPharmaceutical',
            new_name='IdPharmaceutical',
        ),
        migrations.RenameField(
            model_name='vitaminherb',
            old_name='idPharmaceutical',
            new_name='IdPharmaceutical',
        ),
        migrations.AlterUniqueTogether(
            name='medicalbed',
            unique_together={('Number', 'medUnitNumber')},
        ),
        migrations.AlterUniqueTogether(
            name='medicinecasecontains',
            unique_together={('patientHealthcareNum', 'IdPharmaceutical')},
        ),
    ]
