# Generated by Django 4.0 on 2022-02-20 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_idpharmaceutical_drug_idpharmaceutical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('idSchool', models.IntegerField(primary_key=True, serialize=False)),
                ('phoneNum', models.IntegerField()),
                ('image', models.ImageField(upload_to='studentImages')),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('postingId', models.AutoField(primary_key=True, serialize=False)),
                ('startAddress', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('maxPassenger', models.IntegerField()),
                ('numOfPassenger', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostingPassenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPassenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postingPassengerPassenger', to='api.posting')),
                ('postingId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postingPassengerPosting', to='api.posting')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportNum', models.AutoField(primary_key=True, serialize=False)),
                ('reportedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportedId', to='api.account')),
                ('reporterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporterId', to='api.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='medCase',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='deliverycontains',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deliverycontains',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliverycontains',
            name='pharmaceutical',
        ),
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='pharmaceutical',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='IdPharmaceutical',
        ),
        migrations.AlterUniqueTogether(
            name='medicalbed',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='medicalbed',
            name='medUnitNumber',
        ),
        migrations.RemoveField(
            model_name='medicalbed',
            name='occupyingPatientNum',
        ),
        migrations.AlterUniqueTogether(
            name='medicinecasecontains',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='medicinecasecontains',
            name='IdPharmaceutical',
        ),
        migrations.RemoveField(
            model_name='medicinecasecontains',
            name='patientHealthcareNum',
        ),
        migrations.AlterUniqueTogether(
            name='nurseorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nurseorder',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='nurseorder',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='nurseorder',
            name='pharmaceutical',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='primaryNurseId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='secondaryNurseId',
        ),
        migrations.AlterUniqueTogether(
            name='supplierlocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplierlocation',
            name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='supplies',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='vitaminherb',
            name='IdPharmaceutical',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('idSchool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driverAccountId', serialize=False, to='api.account')),
                ('licenseNum', models.IntegerField()),
                ('insurancePolicyNum', models.IntegerField()),
                ('driverHistoryFilePath', models.FileField(upload_to='driverHistory')),
            ],
        ),
        migrations.DeleteModel(
            name='CarriedOutBy',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryContains',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='MedicalBed',
        ),
        migrations.DeleteModel(
            name='MedicalUnit',
        ),
        migrations.DeleteModel(
            name='MedicineCaseContains',
        ),
        migrations.DeleteModel(
            name='NurseOrder',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Pharmaceutical',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierLocation',
        ),
        migrations.DeleteModel(
            name='Supplies',
        ),
        migrations.DeleteModel(
            name='VitaminHerb',
        ),
        migrations.AddField(
            model_name='posting',
            name='driverId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverPostingId', to='api.driver'),
        ),
    ]
